[package]
name = "group_chart"
version = "1.7.0"
authors = ["Jan Guzik <jan.guzik@cs.ox.ac.uk>"]
edition = "2018"

[dependencies]
reqwest= "0.9.19"
serde_derive= "1.0.98"
serde= "1.0.98"
serde_json= "1.0.40"
image = "0.21"
imageproc = "0.18.0"
rusttype = "0.7.7"
num-rational = "0.2.2"
