[package]
name = "group_chart"
version = "1.0.0"
authors = ["Jan Guzik <jan.guzik@cs.ox.ac.uk>"]
edition = "2018"

[dependencies]
reqwest="0.9.5"
serde_derive="1.0.84"
serde="1.0.84"
serde_json="1.0.34"
image = "0.20.1"
